name: baizhan_skill
description: JX3 百战异闻录技能统计工具。
publish_to: "none"
version: 0.1.4+5

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  file_picker: ^11.0.3
  webdav_client: ^1.2.2
  package_info_plus: ^8.3.1
  url_launcher: ^6.3.1
  archive: ^4.2.0
  xml: ^6.6.1
  image: ^4.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/minds/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/baizhan_icon.png
  remove_alpha_ios: true
  background_color_ios: "#173C67"
  windows:
    generate: true
    image_path: assets/icon/baizhan_icon.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/icon/baizhan_icon.png
